/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Mar 28, 2012, 8:24:31 PM
 */

package scoutclient;

import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author John
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    
    Integer teams[] = {11,25,56,75,222,223,224,225,272,303,316,341,357,365,423,433,484,486,708,714,816,834,869,1089,1168,1218,1279,1302,1370,1391,1403,1626,1640,1647,1672,1676,1712,1811,1923,2016,2180,2234,2559,2590,2607,2729,3142,3314,3515,3637,3929,3974,4342};
    int rawData[][];
    String headers[];
    ArrayList<String> absentList = new ArrayList<String>();
    
    public NewJFrame(int[][] e,String[] f) {
        rawData = e;
        headers = f;
        Integer[][] temp = new Integer[e.length][14];
        Integer[][] tempFiltered = new Integer[54][14];
        //Make list of absent Teams
        for (int i = 0; i<e.length; i++){
            if (e[i][2] > 0){
                absentList.add(String.valueOf(i));
            }
        }
        for (int foo=0; foo < e.length; foo++){
            int placeholder = 0;
            for (int fooey = 0; fooey < e[0].length; fooey++){
                if (fooey != 2){
                temp[foo][placeholder] = Integer.valueOf(e[foo][fooey]);
                placeholder++;
                }
            }
        }
        for (int foo=0; foo<e.length;foo++){
            temp[foo][11] = Integer.valueOf(foo);
            System.out.println(temp[foo][11]);
        }
        
        int placeholder = 0;
        for (int i = 0;i< temp.length;i++){
            if (Arrays.asList(teams).contains(temp[i][11]))
            {
                tempFiltered[placeholder] = temp[i];
                System.out.println(tempFiltered[placeholder][11]);
                placeholder++;
            }
        }
        System.out.println(tempFiltered[11][8] + "hello");
        initComponents(tempFiltered,f);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
   /* @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        balanceTimesCheck = new javax.swing.JCheckBox();
        balanceBotsCheck = new javax.swing.JCheckBox();
        pointsAutonCheck = new javax.swing.JCheckBox();
        pointsTeleopCheck = new javax.swing.JCheckBox();
        coopPointsCheck = new javax.swing.JCheckBox();
        balanceBotsFilter = new javax.swing.JTextField();
        pointsAutonFilter = new javax.swing.JTextField();
        balanceTimesFilter = new javax.swing.JTextField();
        pointsTeleopFilter = new javax.swing.JTextField();
        coopPointsFilter = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        applyFilters = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        teamNumber = new javax.swing.JLabel();
        autonPoints = new javax.swing.JLabel();
        teleopPoints = new javax.swing.JLabel();
        coopScoreField = new javax.swing.JLabel();
        balancedWithOnAverage = new javax.swing.JLabel();
        amountOfBalances = new javax.swing.JLabel();
        defensiveScore = new javax.swing.JLabel();
        functioning = new javax.swing.JLabel();
        tipBridgeInAuton = new javax.swing.JLabel();
        fallFromBridge = new javax.swing.JLabel();
        hasHadAWorkingAutonTimes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTabbedPane1.addTab("tab1", jScrollPane2);

        balanceTimesCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        balanceTimesCheck.setText("Has balanced more than times:");

        balanceBotsCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        balanceBotsCheck.setText("Has balanced with more than bots:");

        pointsAutonCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pointsAutonCheck.setText("Has scored more than points in auton:");

        pointsTeleopCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pointsTeleopCheck.setText("Has scored more than points in teleop:");

        coopPointsCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        coopPointsCheck.setText("Has cooperated more than times:");

        balanceBotsFilter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        pointsAutonFilter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        balanceTimesFilter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        pointsTeleopFilter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        coopPointsFilter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Check the box next to the \nfilter you would like to use");

        applyFilters.setText("Apply Filters");
        applyFilters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFiltersPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(coopPointsCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(coopPointsFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(pointsTeleopCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pointsTeleopFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(pointsAutonCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pointsAutonFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(balanceBotsCheck)
                                    .addComponent(balanceTimesCheck))
                                .addGap(114, 114, 114)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(balanceTimesFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(balanceBotsFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(applyFilters)
                        .addGap(70, 70, 70))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balanceTimesCheck)
                    .addComponent(balanceTimesFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(balanceBotsCheck)
                    .addComponent(balanceBotsFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pointsAutonCheck)
                    .addComponent(pointsAutonFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(applyFilters, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pointsTeleopCheck)
                    .addComponent(pointsTeleopFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coopPointsCheck)
                    .addComponent(coopPointsFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(166, 166, 166))
        );

        jTabbedPane1.addTab("tab3", jPanel2);

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                selectedTeamChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                teamSearch(evt);
            }
        });

        jLabel1.setText("Team to search for");

        teamNumber.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        autonPoints.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        autonPoints.setText("Points scored in auton:");

        teleopPoints.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        teleopPoints.setText("Points scored in teleop:");

        coopScoreField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        coopScoreField.setText("Coop Score:");

        balancedWithOnAverage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        balancedWithOnAverage.setText("Balance Score:");

        amountOfBalances.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        amountOfBalances.setText("Amount of Balances:");

        defensiveScore.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        defensiveScore.setText("Defense Score:");

        functioning.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        functioning.setText("Was functioning:");

        tipBridgeInAuton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tipBridgeInAuton.setText("Tip in Auton:");

        fallFromBridge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fallFromBridge.setText("Fell over from Bridge:");

        hasHadAWorkingAutonTimes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hasHadAWorkingAutonTimes.setText("Times had a working auton:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(coopScoreField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(amountOfBalances)
                                    .addComponent(autonPoints)
                                    .addComponent(teleopPoints)
                                    .addComponent(hasHadAWorkingAutonTimes)
                                    .addComponent(balancedWithOnAverage))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipBridgeInAuton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(defensiveScore, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(functioning, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fallFromBridge, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(teamNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(41, 41, 41)
                        .addComponent(teamNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(autonPoints)
                            .addComponent(tipBridgeInAuton))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(teleopPoints)
                                .addGap(18, 18, 18)
                                .addComponent(hasHadAWorkingAutonTimes))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(defensiveScore)
                                .addGap(18, 18, 18)
                                .addComponent(functioning)))
                        .addGap(64, 64, 64)
                        .addComponent(amountOfBalances)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(balancedWithOnAverage)
                            .addComponent(fallFromBridge))
                        .addGap(18, 18, 18)
                        .addComponent(coopScoreField)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab2", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//GEN-FIRST:event_teamSearch
     * private void teamSearch(java.awt.event.KeyEvent evt) {//GEN-HEADEREND:event_teamSearch
     * 
     * handling code here:
}//GEN-LAST:event_teamSearch

//GEN-FIRST:event_selectedTeamChanged
     * private void selectedTeamChanged(javax.swing.event.ListSelectionEvent
     * evt) {//GEN-HEADEREND:event_selectedTeamChanged
// TODO add your handling code here:
}//GEN-LAST:event_selectedTeamChanged

//GEN-FIRST:event_buttonFiltersPressed
     * private void buttonFiltersPressed(java.awt.event.ActionEvent evt) {//GEN-HEADEREND:event_buttonFiltersPressed
//
     * TODO add your handling code here:
}//GEN-LAST:event_buttonFiltersPressed
*/
    
    private void buttonFiltersPressed(java.awt.event.ActionEvent evt) {
        int e[][] = rawData;
        String f[] = headers;
        Integer[][] temp = new Integer[e.length][14];
        Integer[][] tempFiltered = new Integer[54][14];
        for (int foo=0; foo < e.length; foo++){
            int placeholder = 0;
            for (int fooey = 0; fooey < e[0].length; fooey++){
                if (fooey != 2){
                temp[foo][placeholder] = Integer.valueOf(e[foo][fooey]);
                placeholder++;
                }
            }
        }
        for (int foo=0; foo<e.length;foo++){
            temp[foo][11] = Integer.valueOf(foo);
            System.out.println(temp[foo][11]);
        }
        
        int placeholder = 0;
        boolean notNullStupidValueThatIDontWantToMake = false;
        System.out.println(String.valueOf(Arrays.asList(teams).contains(temp[11][11]))+(!balanceTimesCheck.isSelected()||Integer.valueOf(balanceTimesFilter.getText())<=temp[11][8])+String.valueOf(!balanceBotsCheck.isSelected()||Integer.valueOf(balanceBotsFilter.getText())<=temp[11][4])+String.valueOf(!pointsAutonCheck.isSelected()||Integer.valueOf(pointsAutonFilter.getText())<=temp[11][0])+String.valueOf(!pointsTeleopCheck.isSelected()||Integer.valueOf(pointsTeleopFilter.getText())<=temp[11][1])+String.valueOf(!coopPointsCheck.isSelected()||Integer.valueOf(coopPointsFilter.getText())<=temp[11][9]));
        for (int i = 0;i< temp.length;i++){
            if ((Arrays.asList(teams).contains(temp[i][11]))&&(!balanceTimesCheck.isSelected()||Integer.valueOf(balanceTimesFilter.getText())<=temp[i][8])&&(!balanceBotsCheck.isSelected()||Integer.valueOf(balanceBotsFilter.getText())<=temp[i][4])&&(!pointsAutonCheck.isSelected()||Integer.valueOf(pointsAutonFilter.getText())<=temp[i][0])&&(!pointsTeleopCheck.isSelected()||Integer.valueOf(pointsTeleopFilter.getText())<=temp[i][1])&&(!coopPointsCheck.isSelected()||Integer.valueOf(coopPointsFilter.getText())<=temp[i][9]))
            {
                notNullStupidValueThatIDontWantToMake = true;
                tempFiltered[placeholder] = temp[i];
                System.out.println(tempFiltered[placeholder][11]);
                placeholder++;
            }
        }
        System.out.println(notNullStupidValueThatIDontWantToMake);
        if (notNullStupidValueThatIDontWantToMake == true){
            System.out.println("HELLOOOOOOOOOOOOOOOOOOOOOOOOOOOOO");
        jTable1.setModel(new javax.swing.table.DefaultTableModel(tempFiltered,f){
        public Class getColumnClass(int column) {
        Class returnValue;
        if ((column >= 0) && (column < getColumnCount())) {
          returnValue = getValueAt(0, column).getClass();
        } else {
          returnValue = Object.class;
        }
        return returnValue;
      }
    }
);
        jTable1.moveColumn(jTable1.getColumnCount()-1, 0);
        jTable1.moveColumn(3, 1);


        
        notNullStupidValueThatIDontWantToMake = false;
        }
        
        
    }
    
    private void selectedTeamChanged(javax.swing.event.ListSelectionEvent evt) {
        System.out.println("Yello!");
        teamNumber.setText("Team: "+String.valueOf(jList1.getSelectedValue()));
        autonPoints.setText("Points scored in auton: " + rawData[Integer.valueOf(String.valueOf(jList1.getSelectedValue()))][0]);
        teleopPoints.setText("Points scored in teleop: " + rawData[Integer.valueOf(String.valueOf(jList1.getSelectedValue()))][1]);
        hasHadAWorkingAutonTimes.setText("Times had a working auton: " + rawData[Integer.valueOf(String.valueOf(jList1.getSelectedValue()))][6]);
        tipBridgeInAuton.setText("Tip in Auton: " + rawData[Integer.valueOf(String.valueOf(jList1.getSelectedValue()))][7]);
        defensiveScore.setText("Defense Score: " + rawData[Integer.valueOf(String.valueOf(jList1.getSelectedValue()))][4]);
        functioning.setText("Was functioning: " + rawData[Integer.valueOf(String.valueOf(jList1.getSelectedValue()))][8]);
        amountOfBalances.setText("Amount of Balances: " + rawData[Integer.valueOf(String.valueOf(jList1.getSelectedValue()))][9]);
        balancedWithOnAverage.setText("Balance Score: " + rawData[Integer.valueOf(String.valueOf(jList1.getSelectedValue()))][5]);
        fallFromBridge.setText("Fell over from Bridge: " + rawData[Integer.valueOf(String.valueOf(jList1.getSelectedValue()))][11]);
        coopScoreField.setText("Coop Score: " + rawData[Integer.valueOf(String.valueOf(jList1.getSelectedValue()))][10]);
        
    }
    
    private void teamSearch(java.awt.event.KeyEvent evt) {
        System.out.println("yo");
        for (int i = 0; i < jList1.getModel().getSize(); i++){
            System.out.println(String.valueOf(jList1.getModel().getElementAt(i)));
            System.out.println(String.valueOf(jTextField1.getText()));
            if (String.valueOf(jTextField1.getText()).equals(String.valueOf(jList1.getModel().getElementAt(i)))){
                System.out.println("teehee");
                jList1.setSelectedValue(Integer.valueOf(jTextField1.getText()), true);
            }
        }
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents(Integer[][] e,String[] i) {
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){
            public Component prepareRenderer (TableCellRenderer renderer,int Index_row, int Index_col) {
                Component comp = super.prepareRenderer(renderer, Index_row, Index_col);
                 //even index, selected or not selected
                                System.out.println(String.valueOf(jTable1.getValueAt(Index_row, 0)));
                                System.out.println(absentList.toString());
                                System.out.println(absentList.contains(String.valueOf(jTable1.getValueAt(Index_row, 0))));
                                System.out.println(!isCellSelected(Index_row, Index_col));
                if (absentList.contains(String.valueOf(jTable1.getValueAt(Index_row, 0)))&&!isCellSelected(Index_row, Index_col)) {
                    comp.setBackground(Color.LIGHT_GRAY);
                }
                else if(isCellSelected(Index_row, Index_col)){
                    comp.setBackground(Color.BLUE);
                }
                else {
                    comp.setBackground(Color.YELLOW);
                }
                return comp;
                }
        };
        jPanel2 = new javax.swing.JPanel();
        balanceTimesCheck = new javax.swing.JCheckBox();
        balanceBotsCheck = new javax.swing.JCheckBox();
        pointsAutonCheck = new javax.swing.JCheckBox();
        pointsTeleopCheck = new javax.swing.JCheckBox();
        coopPointsCheck = new javax.swing.JCheckBox();
        balanceBotsFilter = new javax.swing.JTextField();
        pointsAutonFilter = new javax.swing.JTextField();
        balanceTimesFilter = new javax.swing.JTextField();
        pointsTeleopFilter = new javax.swing.JTextField();
        coopPointsFilter = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        applyFilters = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        teamNumber = new javax.swing.JLabel();
        autonPoints = new javax.swing.JLabel();
        teleopPoints = new javax.swing.JLabel();
        coopScoreField = new javax.swing.JLabel();
        balancedWithOnAverage = new javax.swing.JLabel();
        amountOfBalances = new javax.swing.JLabel();
        defensiveScore = new javax.swing.JLabel();
        functioning = new javax.swing.JLabel();
        tipBridgeInAuton = new javax.swing.JLabel();
        fallFromBridge = new javax.swing.JLabel();
        hasHadAWorkingAutonTimes = new javax.swing.JLabel();
        

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                teamSearch(evt);
            }
        });
        
        jLabel1.setText("Team to search for");
        
        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(e,i){
      public Class getColumnClass(int column) {
        Class returnValue;
        if ((column >= 0) && (column < getColumnCount())) {
          returnValue = getValueAt(0, column).getClass();
        } else {
          returnValue = Object.class;
        }
        return returnValue;
      }
    }
);
        
        
        jTable1.moveColumn(jTable1.getColumnCount()-1, 0);
        jTable1.moveColumn(3, 1);
        
        jScrollPane2.setViewportView(jTable1);
        
        jTabbedPane1.addTab("Sort Teams", jScrollPane2);
        
        balanceTimesCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        balanceTimesCheck.setText("Has balanced more than times:");

        balanceBotsCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        balanceBotsCheck.setText("Has balanced with more than bots:");

        pointsAutonCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pointsAutonCheck.setText("Has scored more than points in auton:");

        pointsTeleopCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pointsTeleopCheck.setText("Has scored more than points in teleop:");

        coopPointsCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        coopPointsCheck.setText("Has cooperated more than times:");

        balanceBotsFilter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        pointsAutonFilter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        balanceTimesFilter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        pointsTeleopFilter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        coopPointsFilter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Check the box next to the \nfilter you would like to use");

        applyFilters.setText("Apply Filters");
        applyFilters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFiltersPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(coopPointsCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(coopPointsFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(pointsTeleopCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pointsTeleopFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(pointsAutonCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pointsAutonFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(balanceBotsCheck)
                                    .addComponent(balanceTimesCheck))
                                .addGap(114, 114, 114)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(balanceTimesFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(balanceBotsFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(applyFilters)
                        .addGap(70, 70, 70))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balanceTimesCheck)
                    .addComponent(balanceTimesFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(balanceBotsCheck)
                    .addComponent(balanceBotsFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pointsAutonCheck)
                    .addComponent(pointsAutonFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(applyFilters, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pointsTeleopCheck)
                    .addComponent(pointsTeleopFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coopPointsCheck)
                    .addComponent(coopPointsFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(166, 166, 166))
        );

        jTabbedPane1.addTab("<-- Filters", jPanel2);
        
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                selectedTeamChanged(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        
        jTable1.setAutoCreateRowSorter(true);
        
        teamNumber.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        
        autonPoints.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        autonPoints.setText("Points scored in auton:");

        teleopPoints.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        teleopPoints.setText("Points scored in teleop:");

        coopScoreField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        coopScoreField.setText("Coop Score:");

        balancedWithOnAverage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        balancedWithOnAverage.setText("Balance Score:");

        amountOfBalances.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        amountOfBalances.setText("Amount of Balances:");

        defensiveScore.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        defensiveScore.setText("Defense Score:");

        functioning.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        functioning.setText("Was functioning:");

        tipBridgeInAuton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tipBridgeInAuton.setText("Tip in Auton:");

        fallFromBridge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fallFromBridge.setText("Fell over from Bridge:");

        hasHadAWorkingAutonTimes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hasHadAWorkingAutonTimes.setText("Times had a working auton:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(coopScoreField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(amountOfBalances)
                                    .addComponent(autonPoints)
                                    .addComponent(teleopPoints)
                                    .addComponent(hasHadAWorkingAutonTimes)
                                    .addComponent(balancedWithOnAverage))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipBridgeInAuton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(defensiveScore, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(functioning, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fallFromBridge, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(teamNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(41, 41, 41)
                        .addComponent(teamNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(autonPoints)
                            .addComponent(tipBridgeInAuton))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(teleopPoints)
                                .addGap(18, 18, 18)
                                .addComponent(hasHadAWorkingAutonTimes))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(defensiveScore)
                                .addGap(18, 18, 18)
                                .addComponent(functioning)))
                        .addGap(64, 64, 64)
                        .addComponent(amountOfBalances)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(balancedWithOnAverage)
                            .addComponent(fallFromBridge))
                        .addGap(18, 18, 18)
                        .addComponent(coopScoreField)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
                .addContainerGap())
        );
        
        jList1.setListData(teams);

        jTabbedPane1.addTab("Search Teams", jPanel1);

        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>
                 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountOfBalances;
    private javax.swing.JButton applyFilters;
    private javax.swing.JLabel autonPoints;
    private javax.swing.JCheckBox balanceBotsCheck;
    private javax.swing.JTextField balanceBotsFilter;
    private javax.swing.JCheckBox balanceTimesCheck;
    private javax.swing.JTextField balanceTimesFilter;
    private javax.swing.JLabel balancedWithOnAverage;
    private javax.swing.JCheckBox coopPointsCheck;
    private javax.swing.JTextField coopPointsFilter;
    private javax.swing.JLabel coopScoreField;
    private javax.swing.JLabel defensiveScore;
    private javax.swing.JLabel fallFromBridge;
    private javax.swing.JLabel functioning;
    private javax.swing.JLabel hasHadAWorkingAutonTimes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JCheckBox pointsAutonCheck;
    private javax.swing.JTextField pointsAutonFilter;
    private javax.swing.JCheckBox pointsTeleopCheck;
    private javax.swing.JTextField pointsTeleopFilter;
    private javax.swing.JLabel teamNumber;
    private javax.swing.JLabel teleopPoints;
    private javax.swing.JLabel tipBridgeInAuton;
    // End of variables declaration//GEN-END:variables

}
